package com.phantomwing.rusticdelight.potion;

import com.phantomwing.rusticdelight.RusticDelight;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.alchemy.Potion;

/**
 * The potions themselves. Their brewing recipes are data-driven as of 26.3 (which deleted
 * {@code PotionBrewing}) and are generated by
 * {@code com.phantomwing.rusticdelight.datagen.ModRecipeProvider}, where the {@code enable_potions}
 * and {@code enable_coffee} config gates are applied as datapack conditions.
 */
public class ModPotions {
    // Potions
    public static final Holder<Potion> HASTE_POTION = register("haste", MobEffects.HASTE, 3600);
    public static final Holder<Potion> LONG_HASTE_POTION = register("long_haste", "haste", MobEffects.HASTE, 9600, 0);
    public static final Holder<Potion> STRONG_HASTE_POTION = register("strong_haste", "haste", MobEffects.HASTE, 1800, 1);

    private static Holder<Potion> register(String name, Holder<MobEffect> effect, int duration) {
        return Registry.registerForHolder(
                BuiltInRegistries.POTION,
                Identifier.fromNamespaceAndPath(RusticDelight.MOD_ID, name),
                new Potion(name, new MobEffectInstance(effect, duration, 0))
        );
    }

    private static Holder<Potion> register(String name, String potionName, Holder<MobEffect> effect, int duration, int amplifier) {
        return Registry.registerForHolder(
                BuiltInRegistries.POTION,
                Identifier.fromNamespaceAndPath(RusticDelight.MOD_ID, name),
                new Potion(potionName, new MobEffectInstance(effect, duration, amplifier))
        );
    }

    public static void registerModPotions() {
        RusticDelight.LOGGER.info("Registering potions for " + RusticDelight.MOD_ID);
    }
}
